spring:
  application:
    name: demo
  datasource:
    url: jdbc:h2:mem:task;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
    auto-commit: false
    hikari:
      auto-commit: false
      maximum-pool-size: 5
  jpa:
    hibernate:
      batch_fetch_style: dynamic
      jdbc:
        fetch_size: 50
        batch_size: 10
    properties:
      hibernate.hbm2ddl.auto: update
  h2:
    console:
      enabled: true
